language: objective-c

matrix:
  include:
    - osx_image: xcode8.3
    - osx_image: xcode9.0

branches:
  only:
  - master
  - buildmatrix
  global:
  - NODE_VERSION=stable
install:
- brew -v
- brew update
- brew -v
- brew install yarn
- export CODE_SIGNING_REQUIRED=NO
- brew tap wix/brew
- brew install applesimutils --HEAD
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
- export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
- npm install -g lerna@2.1.2 >/dev/null 2>&1
- npm install -g react-native-cli >/dev/null 2>&1
- npm install -g detox-cli >/dev/null 2>&1
- gem install xcpretty >/dev/null 2>&1
script:
- ./scripts/ci.sh
notifications:
  email: true
  slack:
    secure: ExAwGcI4WlRoi/F2AKMds2eNQZ90susGT2k/CSU1ZQdTL5jaeMW6/i86Uz6Goilnd7qL/1GhlHF9Q48yYtctLVg4zSKH3uclHDDtPfWsF/R7+UWBPYtvhuW2VvL4ota8b0QzUlTz3iS0G3iD4AFqnAZUgYqjSeF1arv+YKOTEXzGyPtj3xjD9TSSjamnSEgGd18RRKpG8FWQr631yOSucikUsYcetV8bUTs6PtjcIC0XK1d1Nv/eMJxSwTQCAptQbxPTO0FBEEH+lQ6H5oQ7mvyNQ7BBUEunUWkUsCh85SsqHLbnCaiPojmI8ICUJBDNSDvzvyt1JJOxnjWtXlLu5xLOQRYeMvr9p66uBMTxTw2LXagSw4bxAf8LHXK/EOssTv+bE6gujNga0FF3jOLTDUZF93OT7TCsrVQrIkiKBl/YoJVc137dz/fUz3wA/JkmqQIV0i9BMUVNYlBGg3J9Omo8nQXTEvqNpYdSfWEm6cZT73kRrdiuittcBXUeWaTkqThmL8KMO5u+InUQhOhhxMmZ/u3DZRTxtHu9ndOdMrWaOmDj4MXpTsml6qelFHMdQoNQubUgdpSb0H0KvGObnQwFR3V2alPT6Ovx1e+XzjBiV2CNP3jHci52JGAlPtGRxctiXUYL9TZYgpJdO/IxJR/lAhA7ZJLsfHGL4LUF65o=
    secure: KyGnFJDelMPoz0MklVWYxYYaMakI/AMSzsLO+3ouF+oksHKAqwWSG7rzbAeb1sQGj0uc3t2cIbRDYMPFCbvnhOC+Z2u2qg6xHlrYsaFO6+yNro0s5WxQ+KvJ4P+VqlqKi9XSE9G+kwDz/0FbERJ5sOnDa8ueZ8KDfJEs/ZZRQmedw3bV1p0WWzJKNRsLk3bIbHYk9UXLcA42/QRlymrhBnwVHr6LZfOE19BV5wHScFp/hGz8ajPo8+KCvgUcM/sCIZbeId8BDMc+W91Tk9YzZcxRP5/upq3Sl3FFrPo8LYrJq+tdCGlnHQDBv+yuEC1WlM90V4bgRLqs0w1QuQsFL3adJvmNXHb80gwShmNaY4aS52/jzgbi+mBX2wVAm0VXwLPXnWDo2iIOGkELGBq3PJwwO8W4ES2m0LfLjOTrYG+PLB5FIWae++gDhHDJ9f9tUSK+SxXVvGHRPXNOnpqecGBYxurQhWDuumpe49S2T8Zx+uotjKYRm9ECW4IL8JIzPEVYkRpSoau/zH6urUacDnfFKtvhYDq89/cc/Y3vwhWY8+ixvQH22+HZc3b54KTY/o67Q3IXsAP/yx7AexvJuh56GCgONPchsJ0PX4lIytzyHKwCzQC2UuqgKismDVTlsdlSijfNnaXN2HEhbugwrXJPP+6Kq/TMlPuDSjfi8OA=
