name: Broken Links Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  remark:
    name: Remark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610
        with:
          node-version-file: '.nvmrc'
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: NPQ_PKG_MGR=yarn npx npq install --immutable
      - run: yarn remark -r .remarkrc.nightly.mjs .
