name: Rapid Test

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/rapid-test.yml'
      - 'detox/**'
      - 'generation/**'
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/rapid-test.yml'
      - 'detox/**'
      - 'generation/**'

jobs:

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610
        with:
          node-version-file: '.nvmrc'
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yes | npx npq install --immutable
        env:
          NPQ_PKG_MGR: yarn
          DETOX_DISABLE_POD_INSTALL: true
          DETOX_DISABLE_POSTINSTALL: true
      - name: Lint source project
        run: yarn lint
        working-directory: detox
      - name: Lint test project
        run: yarn lint
        working-directory: detox/test
      - name: Typings
        run: yarn test
        working-directory: detox/test
      - name: Unit tests
        run: yarn unit
        working-directory: detox
      - name: Integration tests
        run: yarn integration
        working-directory: detox/test
      - name: Generation tests
        run: yarn test
        working-directory: generation
      - name: Pack Allure results
        run: zip -r allure-results.zip detox/allure-results detox/test/allure-results generation/allure-results
      - name: Upload Allure results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: allure-results-linux
          path: allure-results.zip

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610
        with:
          node-version-file: '.nvmrc'
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: echo y | npx npq install --immutable
        shell: bash
        env:
          NPQ_PKG_MGR: yarn
          DETOX_DISABLE_POD_INSTALL: true
          DETOX_DISABLE_POSTINSTALL: true
      - name: Unit tests
        run: yarn unit --coverageThreshold "{}"
        working-directory: detox
      - name: Integration tests
        run: yarn integration
        working-directory: detox/test
      - name: Pack Allure results
        run: |
          Compress-Archive -Path detox/allure-results -DestinationPath allure-results.zip
        shell: pwsh
      - name: Upload Allure results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: allure-results-windows
          path: allure-results.zip
