name: Rapid Test

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/rapid-test.yml'
      - 'detox/**'
      - 'generation/**'
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/rapid-test.yml'
      - 'detox/**'
      - 'generation/**'

jobs:

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Enable Corepack
        run: corepack enable
      - name: Security check (npq)
        run: npx npq@3.14.0 install --pkgMgr yarn --dry-run
      - name: Install dependencies
        run: yarn install --immutable
        env:
          DETOX_DISABLE_POD_INSTALL: true
          DETOX_DISABLE_POSTINSTALL: true
      - name: Lint source project
        run: yarn lint
        working-directory: detox
      - name: Lint test project
        run: yarn lint
        working-directory: detox/test
      - name: Typings
        run: yarn test
        working-directory: detox/test
      - name: Unit tests
        run: yarn unit
        working-directory: detox
      - name: Integration tests
        run: yarn integration
        working-directory: detox/test
      - name: Generation tests
        run: yarn test
        working-directory: generation
      - name: Pack Allure results
        run: zip -r allure-results.zip detox/allure-results detox/test/allure-results generation/allure-results
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-linux
          path: allure-results.zip

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Enable Corepack
        run: corepack enable
      - name: Security check (npq)
        run: npx npq@3.14.0 install --pkgMgr yarn --dry-run
      - name: Install dependencies
        run: yarn install --immutable
        env:
          DETOX_DISABLE_POD_INSTALL: true
          DETOX_DISABLE_POSTINSTALL: true
      - name: Unit tests
        run: yarn unit --coverageThreshold "{}"
        working-directory: detox
      - name: Integration tests
        run: yarn integration
        working-directory: detox/test
      - name: Pack Allure results
        run: |
          Compress-Archive -Path detox/allure-results -DestinationPath allure-results.zip
        shell: pwsh
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-windows
          path: allure-results.zip
