name: Purge old domains
on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Older than (days)'
        required: false

  schedule:
    - cron: '0 3 * * *'
jobs:
  surge-purge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610
        with:
          node-version-file: '.nvmrc'
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yes | npx npq install --immutable
        env:
          NPQ_PKG_MGR: yarn
      - name: Teardown old domains
        run: yarn zx scripts/purge_expired_domains.mjs --olderThan ${{ github.event.inputs.days || '10' }}
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
