name: Website

on:
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/website.yml'
      - 'docs/**'
      - 'website/**'
  push:
    branches: [master]
    paths:
      - '.github/workflows/website.yml'
      - 'docs/**'
      - 'website/**'

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610
        with:
          node-version-file: '.nvmrc'
      - name: Enable Corepack
        run: corepack enable
      - name: Install and build
        working-directory: ./website
        env:
          NPQ_PKG_MGR: yarn
        run: |
          yes | npx npq install
          yarn build
  gh-release:
    if: github.event_name != 'pull_request'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610
        with:
          node-version-file: '.nvmrc'
      - name: Enable Corepack
        run: corepack enable
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
          NPQ_PKG_MGR: yarn
        run: |
          git config --global user.email "mobile1@wix.com"
          git config --global user.name "mobilewix"
          cd website/
          yes | npx npq install
          yarn build
          yarn docusaurus deploy
  performance:
    needs: gh-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - run: mkdir -p ${{ github.workspace }}/tmp/artifacts
      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: 'https://wix.github.io/Detox/,https://wix.github.io/Detox/docs/next/demo/'
          outputDirectory: ${{ github.workspace }}/tmp/artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: Lighthouse reports
          path: ${{ github.workspace }}/tmp/artifacts
